LDADD += -L ../talib1/ -ltalib1 
LDADD += -L ../talib2/ -ltalib2
LDADD += -L ../talib3/ -ltalib3

#LDADD += -L ../../../liboqs_ta/liboqs-main/build/lib -loqs
#LDADD += -L ../../../../../usr/lib/x86_64-linux-gnu -lc
#LDADD += -L /home/kidds/liboqs/liboqs-main/build/lib -loqs \	
# The UUID for the Trusted Application
BINARY=19038f64-871d-4773-b1f5-878697745eee

-include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk
